/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'displayName' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
});
export const Level = IDL.Variant({
  'neon_night' : IDL.Null,
  'city_streets' : IDL.Null,
  'underground_tunnel' : IDL.Null,
  'highway_drift' : IDL.Null,
  'bonus_challenge' : IDL.Null,
  'downtown_rush' : IDL.Null,
});
export const Time = IDL.Int;
export const ScoreEntry = IDL.Record({
  'player' : IDL.Principal,
  'level' : Level,
  'score' : IDL.Nat,
  'timestamp' : Time,
});
export const Upgrade = IDL.Variant({
  'nitro_boost' : IDL.Null,
  'top_speed' : IDL.Null,
  'acceleration' : IDL.Null,
  'handling' : IDL.Null,
});
export const CarType = IDL.Variant({
  'muscle' : IDL.Null,
  'basic' : IDL.Null,
  'sports' : IDL.Null,
  'drift' : IDL.Null,
  'supercar' : IDL.Null,
});
export const PlayerProgress = IDL.Record({
  'unlockedUpgrades' : IDL.Vec(Upgrade),
  'coins' : IDL.Nat,
  'lastPlayedLevel' : IDL.Opt(Level),
  'settings' : IDL.Record({ 'music' : IDL.Bool, 'sound' : IDL.Bool }),
  'unlockedCars' : IDL.Vec(CarType),
  'unlockedLevels' : IDL.Vec(Level),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPlayerScores' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(ScoreEntry)],
      ['query'],
    ),
  'getProgress' : IDL.Func([], [IDL.Opt(PlayerProgress)], ['query']),
  'getTopScores' : IDL.Func([IDL.Nat], [IDL.Vec(ScoreEntry)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveProgress' : IDL.Func([PlayerProgress], [], []),
  'submitScore' : IDL.Func([IDL.Nat, Level], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'displayName' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
  });
  const Level = IDL.Variant({
    'neon_night' : IDL.Null,
    'city_streets' : IDL.Null,
    'underground_tunnel' : IDL.Null,
    'highway_drift' : IDL.Null,
    'bonus_challenge' : IDL.Null,
    'downtown_rush' : IDL.Null,
  });
  const Time = IDL.Int;
  const ScoreEntry = IDL.Record({
    'player' : IDL.Principal,
    'level' : Level,
    'score' : IDL.Nat,
    'timestamp' : Time,
  });
  const Upgrade = IDL.Variant({
    'nitro_boost' : IDL.Null,
    'top_speed' : IDL.Null,
    'acceleration' : IDL.Null,
    'handling' : IDL.Null,
  });
  const CarType = IDL.Variant({
    'muscle' : IDL.Null,
    'basic' : IDL.Null,
    'sports' : IDL.Null,
    'drift' : IDL.Null,
    'supercar' : IDL.Null,
  });
  const PlayerProgress = IDL.Record({
    'unlockedUpgrades' : IDL.Vec(Upgrade),
    'coins' : IDL.Nat,
    'lastPlayedLevel' : IDL.Opt(Level),
    'settings' : IDL.Record({ 'music' : IDL.Bool, 'sound' : IDL.Bool }),
    'unlockedCars' : IDL.Vec(CarType),
    'unlockedLevels' : IDL.Vec(Level),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPlayerScores' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(ScoreEntry)],
        ['query'],
      ),
    'getProgress' : IDL.Func([], [IDL.Opt(PlayerProgress)], ['query']),
    'getTopScores' : IDL.Func([IDL.Nat], [IDL.Vec(ScoreEntry)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveProgress' : IDL.Func([PlayerProgress], [], []),
    'submitScore' : IDL.Func([IDL.Nat, Level], [], []),
  });
};

export const init = ({ IDL }) => { return []; };