/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type CarType = { 'muscle' : null } |
  { 'basic' : null } |
  { 'sports' : null } |
  { 'drift' : null } |
  { 'supercar' : null };
export type Level = { 'neon_night' : null } |
  { 'city_streets' : null } |
  { 'underground_tunnel' : null } |
  { 'highway_drift' : null } |
  { 'bonus_challenge' : null } |
  { 'downtown_rush' : null };
export interface PlayerProgress {
  'unlockedUpgrades' : Array<Upgrade>,
  'coins' : bigint,
  'lastPlayedLevel' : [] | [Level],
  'settings' : { 'music' : boolean, 'sound' : boolean },
  'unlockedCars' : Array<CarType>,
  'unlockedLevels' : Array<Level>,
}
export interface ScoreEntry {
  'player' : Principal,
  'level' : Level,
  'score' : bigint,
  'timestamp' : Time,
}
export type Time = bigint;
export type Upgrade = { 'nitro_boost' : null } |
  { 'top_speed' : null } |
  { 'acceleration' : null } |
  { 'handling' : null };
export interface UserProfile { 'displayName' : [] | [string], 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPlayerScores' : ActorMethod<[Principal], Array<ScoreEntry>>,
  'getProgress' : ActorMethod<[], [] | [PlayerProgress]>,
  'getTopScores' : ActorMethod<[bigint], Array<ScoreEntry>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveProgress' : ActorMethod<[PlayerProgress], undefined>,
  'submitScore' : ActorMethod<[bigint, Level], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];