/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface ScoreEntry {
    player: Principal;
    level: Level;
    score: bigint;
    timestamp: Time;
}
export interface PlayerProgress {
    unlockedUpgrades: Array<Upgrade>;
    coins: bigint;
    lastPlayedLevel?: Level;
    settings: {
        music: boolean;
        sound: boolean;
    };
    unlockedCars: Array<CarType>;
    unlockedLevels: Array<Level>;
}
export interface UserProfile {
    displayName?: string;
    name: string;
}
export enum CarType {
    muscle = "muscle",
    basic = "basic",
    sports = "sports",
    drift = "drift",
    supercar = "supercar"
}
export enum Level {
    neon_night = "neon_night",
    city_streets = "city_streets",
    underground_tunnel = "underground_tunnel",
    highway_drift = "highway_drift",
    bonus_challenge = "bonus_challenge",
    downtown_rush = "downtown_rush"
}
export enum Upgrade {
    nitro_boost = "nitro_boost",
    top_speed = "top_speed",
    acceleration = "acceleration",
    handling = "handling"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getPlayerScores(player: Principal): Promise<Array<ScoreEntry>>;
    getProgress(): Promise<PlayerProgress | null>;
    getTopScores(limit: bigint): Promise<Array<ScoreEntry>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveProgress(progress: PlayerProgress): Promise<void>;
    submitScore(score: bigint, level: Level): Promise<void>;
}
import type { CarType as _CarType, Level as _Level, PlayerProgress as _PlayerProgress, ScoreEntry as _ScoreEntry, Time as _Time, Upgrade as _Upgrade, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlayerScores(arg0: Principal): Promise<Array<ScoreEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayerScores(arg0);
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayerScores(arg0);
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProgress(): Promise<PlayerProgress | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProgress();
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProgress();
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTopScores(arg0: bigint): Promise<Array<ScoreEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTopScores(arg0);
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTopScores(arg0);
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n25(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n25(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveProgress(arg0: PlayerProgress): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveProgress(to_candid_PlayerProgress_n27(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveProgress(to_candid_PlayerProgress_n27(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async submitScore(arg0: bigint, arg1: Level): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitScore(arg0, to_candid_Level_n32(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitScore(arg0, to_candid_Level_n32(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_CarType_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CarType): CarType {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_Level_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Level): Level {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_PlayerProgress_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlayerProgress): PlayerProgress {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_ScoreEntry_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ScoreEntry): ScoreEntry {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Upgrade_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Upgrade): Upgrade {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PlayerProgress]): PlayerProgress | null {
    return value.length === 0 ? null : from_candid_PlayerProgress_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Level]): Level | null {
    return value.length === 0 ? null : from_candid_Level_n12(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    player: Principal;
    level: _Level;
    score: bigint;
    timestamp: _Time;
}): {
    player: Principal;
    level: Level;
    score: bigint;
    timestamp: Time;
} {
    return {
        player: value.player,
        level: from_candid_Level_n12(_uploadFile, _downloadFile, value.level),
        score: value.score,
        timestamp: value.timestamp
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    unlockedUpgrades: Array<_Upgrade>;
    coins: bigint;
    lastPlayedLevel: [] | [_Level];
    settings: {
        music: boolean;
        sound: boolean;
    };
    unlockedCars: Array<_CarType>;
    unlockedLevels: Array<_Level>;
}): {
    unlockedUpgrades: Array<Upgrade>;
    coins: bigint;
    lastPlayedLevel?: Level;
    settings: {
        music: boolean;
        sound: boolean;
    };
    unlockedCars: Array<CarType>;
    unlockedLevels: Array<Level>;
} {
    return {
        unlockedUpgrades: from_candid_vec_n17(_uploadFile, _downloadFile, value.unlockedUpgrades),
        coins: value.coins,
        lastPlayedLevel: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.lastPlayedLevel)),
        settings: value.settings,
        unlockedCars: from_candid_vec_n21(_uploadFile, _downloadFile, value.unlockedCars),
        unlockedLevels: from_candid_vec_n24(_uploadFile, _downloadFile, value.unlockedLevels)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    displayName: [] | [string];
    name: string;
}): {
    displayName?: string;
    name: string;
} {
    return {
        displayName: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.displayName)),
        name: value.name
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    neon_night: null;
} | {
    city_streets: null;
} | {
    underground_tunnel: null;
} | {
    highway_drift: null;
} | {
    bonus_challenge: null;
} | {
    downtown_rush: null;
}): Level {
    return "neon_night" in value ? Level.neon_night : "city_streets" in value ? Level.city_streets : "underground_tunnel" in value ? Level.underground_tunnel : "highway_drift" in value ? Level.highway_drift : "bonus_challenge" in value ? Level.bonus_challenge : "downtown_rush" in value ? Level.downtown_rush : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    nitro_boost: null;
} | {
    top_speed: null;
} | {
    acceleration: null;
} | {
    handling: null;
}): Upgrade {
    return "nitro_boost" in value ? Upgrade.nitro_boost : "top_speed" in value ? Upgrade.top_speed : "acceleration" in value ? Upgrade.acceleration : "handling" in value ? Upgrade.handling : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    muscle: null;
} | {
    basic: null;
} | {
    sports: null;
} | {
    drift: null;
} | {
    supercar: null;
}): CarType {
    return "muscle" in value ? CarType.muscle : "basic" in value ? CarType.basic : "sports" in value ? CarType.sports : "drift" in value ? CarType.drift : "supercar" in value ? CarType.supercar : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Upgrade>): Array<Upgrade> {
    return value.map((x)=>from_candid_Upgrade_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CarType>): Array<CarType> {
    return value.map((x)=>from_candid_CarType_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Level>): Array<Level> {
    return value.map((x)=>from_candid_Level_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ScoreEntry>): Array<ScoreEntry> {
    return value.map((x)=>from_candid_ScoreEntry_n10(_uploadFile, _downloadFile, x));
}
function to_candid_CarType_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CarType): _CarType {
    return to_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function to_candid_Level_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Level): _Level {
    return to_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function to_candid_PlayerProgress_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlayerProgress): _PlayerProgress {
    return to_candid_record_n28(_uploadFile, _downloadFile, value);
}
function to_candid_Upgrade_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Upgrade): _Upgrade {
    return to_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n26(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    displayName?: string;
    name: string;
}): {
    displayName: [] | [string];
    name: string;
} {
    return {
        displayName: value.displayName ? candid_some(value.displayName) : candid_none(),
        name: value.name
    };
}
function to_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    unlockedUpgrades: Array<Upgrade>;
    coins: bigint;
    lastPlayedLevel?: Level;
    settings: {
        music: boolean;
        sound: boolean;
    };
    unlockedCars: Array<CarType>;
    unlockedLevels: Array<Level>;
}): {
    unlockedUpgrades: Array<_Upgrade>;
    coins: bigint;
    lastPlayedLevel: [] | [_Level];
    settings: {
        music: boolean;
        sound: boolean;
    };
    unlockedCars: Array<_CarType>;
    unlockedLevels: Array<_Level>;
} {
    return {
        unlockedUpgrades: to_candid_vec_n29(_uploadFile, _downloadFile, value.unlockedUpgrades),
        coins: value.coins,
        lastPlayedLevel: value.lastPlayedLevel ? candid_some(to_candid_Level_n32(_uploadFile, _downloadFile, value.lastPlayedLevel)) : candid_none(),
        settings: value.settings,
        unlockedCars: to_candid_vec_n34(_uploadFile, _downloadFile, value.unlockedCars),
        unlockedLevels: to_candid_vec_n37(_uploadFile, _downloadFile, value.unlockedLevels)
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Upgrade): {
    nitro_boost: null;
} | {
    top_speed: null;
} | {
    acceleration: null;
} | {
    handling: null;
} {
    return value == Upgrade.nitro_boost ? {
        nitro_boost: null
    } : value == Upgrade.top_speed ? {
        top_speed: null
    } : value == Upgrade.acceleration ? {
        acceleration: null
    } : value == Upgrade.handling ? {
        handling: null
    } : value;
}
function to_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Level): {
    neon_night: null;
} | {
    city_streets: null;
} | {
    underground_tunnel: null;
} | {
    highway_drift: null;
} | {
    bonus_challenge: null;
} | {
    downtown_rush: null;
} {
    return value == Level.neon_night ? {
        neon_night: null
    } : value == Level.city_streets ? {
        city_streets: null
    } : value == Level.underground_tunnel ? {
        underground_tunnel: null
    } : value == Level.highway_drift ? {
        highway_drift: null
    } : value == Level.bonus_challenge ? {
        bonus_challenge: null
    } : value == Level.downtown_rush ? {
        downtown_rush: null
    } : value;
}
function to_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CarType): {
    muscle: null;
} | {
    basic: null;
} | {
    sports: null;
} | {
    drift: null;
} | {
    supercar: null;
} {
    return value == CarType.muscle ? {
        muscle: null
    } : value == CarType.basic ? {
        basic: null
    } : value == CarType.sports ? {
        sports: null
    } : value == CarType.drift ? {
        drift: null
    } : value == CarType.supercar ? {
        supercar: null
    } : value;
}
function to_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Upgrade>): Array<_Upgrade> {
    return value.map((x)=>to_candid_Upgrade_n30(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<CarType>): Array<_CarType> {
    return value.map((x)=>to_candid_CarType_n35(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Level>): Array<_Level> {
    return value.map((x)=>to_candid_Level_n32(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
